PixelExperience/wiki

_data/devices/TP1803.yml, pages/build/TP1803.md, pages/info/TP1803.md, pages/install/TP1803.md, pages/update/TP1803.md, pages/upgrade/TP1803.md
Signed-off-by: Kuba Wojciechowski <nullbytepl@gmail.com>
=> Add Nubia Mini 5G

_data/devices/X01AD.yml, pages/build/X01AD.md, pages/info/X01AD.md, pages/install/X01AD.md, pages/update/X01AD.md, pages/upgrade/X01AD.md
Signed-off-by: iamsaalim <saalimquadri1@gmail.com>
=> Add Asus X01AD

_data/devices/polaris.yml
Signed-off-by: Chenyang Zhong <zhongcy95@gmail.com>
=> wiki: update polaris to use PE recovery

_includes/templates/recovery_install_fastboot_xiaomi_begonia.md
=> begonia: Update Download Link For CFW Zip

_data/devices/beckham.yml, pages/build/beckham.md, pages/info/beckham.md, pages/install/beckham.md, pages/update/beckham.md, pages/upgrade/beckham.md
Change-Id: Ib2f92ed2962d559c09d686de142f5dc70c2fa652
=> wiki: devices: Add Moto Z3 Play (beckham)

_data/devices/apollo.yml, pages/build/apollo.md, pages/info/apollo.md, pages/install/apollo.md, pages/update/apollo.md, pages/upgrade/apollo.md
=> Add Redmi K30S/Mi 10T/Mi 10T Pro

_data/devices/cepheus.yml
ref: https://www.mi.com/global/mi9/specs/
=> cepheus: Clean up

_data/devices/mojito.yml, pages/build/mojito.md, pages/info/mojito.md, pages/install/mojito.md, pages/update/mojito.md, pages/upgrade/mojito.md
=> Add Redmi Note 10

_data/devices/mojito.yml, _includes/templates/recovery_install_fastboot_xiaomi_virtual_ab.md, test/schema-06.yml
* Add virtual AB install method
=> Update installation method for mojito

_data/devices/RMX1971.yml
Signed-off-by: MadhavSaladi <baaswanthmadhav@gmail.com>
=> Add eleven, eleven_plus for RMX1971

_data/devices/sweet.yml, pages/build/sweet.md, pages/info/sweet.md, pages/install/sweet.md, pages/update/sweet.md, pages/upgrade/sweet.md
=> Add Redmi Note 10 Pro/Max

_data/devices/hotdogb.yml, pages/build/hotdogb.md, pages/fw_update/hotdogb.md, pages/info/hotdogb.md, pages/install/hotdogb.md, pages/update/hotdogb.md, pages/upgrade/hotdogb.md
Change-Id: I4f39d14336139ae0fe286b93c6859a4e968d6517
=> wiki: Add OnePlus 7T (hotdogb)

_data/devices/tucana.yml, pages/build/tucana.md, pages/info/tucana.md, pages/install/tucana.md, pages/update/tucana.md, pages/upgrade/tucana.md
Signed-off-by: Henrique Pereira <henrique.pereira@signativa.com.br>
=> wiki: Add tucana

_data/devices/alioth.yml, pages/build/alioth.md, pages/info/alioth.md, pages/install/alioth.md, pages/update/alioth.md, pages/upgrade/alioth.md
Signed-off-by: Zinadin Zidan <zidan.roking@gmail.com>
=> Add POCO F3 / Redmi K40 / Mi 11X

_data/devices/vayu.yml, pages/build/vayu.md, pages/info/vayu.md, pages/install/vayu.md, pages/update/vayu.md, pages/upgrade/vayu.md
Signed-off-by: Alisson Grizotti <alisson1397@hotmail.com>
=> Add POCO X3 PRO

_data/devices/surya.yml
Signed-off-by: chrisw444 <wandersonrodriguesf1@gmail.com>
=> Add Poco X3 again

_data/devices/lmi.yml, pages/build/lmi.md, pages/info/lmi.md, pages/install/lmi.md, pages/update/lmi.md, pages/upgrade/lmi.md
Signed-off-by: Alexandre Rangel <mamutal91@gmail.com>
=> Add Poco F2 Pro

_data/devices/lava.yml, pages/build/lava.md, pages/info/lava.md, pages/install/lava.md, pages/update/lava.md, pages/upgrade/lava.md, test/schema-06.yml
Signed-off-by: SparXFusion <s2234nadar@gmail.com>
=> wiki: Add Xiaomi Redmi 9 Prime / Poco M2 (lava)

_data/devices/alioth.yml
- Also correct release date for Mi 11X
=> alioth: Add release dates for Poco F3 and Redmi K40 Pro

_data/devices/zippo.yml, pages/build/zippo.md, pages/info/zippo.md, pages/install/zippo.md, pages/update/zippo.md, pages/upgrade/zippo.md
Signed-off-by: Lucchetto <lucchetto.tie@live.com>
=> wiki: Add Lenovo Z6 Pro (zippo)

_data/devices/mojito.yml
We have a 2+6 configuration
https://www.gsmarena.com/xiaomi_redmi_note_10-10247.php
=> mojito: fix cpu core and freq configuration

_data/devices/renoir.yml, _includes/templates/device_specific/before_install_renoir.md, pages/build/renoir.md, pages/info/renoir.md, pages/install/renoir.md, pages/update/renoir.md, pages/upgrade/renoir.md, test/schema-06.yml
=> Add Mi 11 Lite 5G (renoir) to wiki

_data/devices/venus.yml, pages/build/venus.md, pages/info/venus.md, pages/install/venus.md, pages/update/venus.md, pages/upgrade/venus.md
Signed-off-by: Chenyang Zhong <zhongcy95@gmail.com>
=> wiki: add Mi 11 (venus)

_data/devices/laurel_sprout.yml
Signed-off-by: zlewchan <wiktorusyt@protonmail.ch>
=> wiki: Bring back laurel_sprout to life!

_data/devices/kane.yml, _includes/templates/device_specific/before_recovery_install_moto_exynos_9610.md, pages/build/kane.md, pages/info/kane.md, pages/install/kane.md, pages/update/kane.md, pages/upgrade/kane.md
Co-authored-by: Nolen Johnson <johnsonnolen@gmail.com>
Signed-off-by: zlewchan <wiktorusyt@protonmail.ch>
=> wiki: Add kane

_data/devices/renoir.yml, _includes/templates/device_specific/before_install_renoir.md
From now firmware is included in ROM zip
Signed-off-by: ArixElo <patroxgamer@gmail.com>
=> renoir: Remove firmware installation step

_data/devices/kane.yml
Major issues with SIM Cards/Hotspot were reported on this model, I'm in process of debugging them. We shouldn't mislead the users by marking it as supported
Signed-off-by: zlewchan <wiktorusyt@protonmail.ch>
=> kane: Temporarily drop support for XT1970-3

_data/devices/jasmine_sprout.yml
Along with processor name changes
=> Devices: Bring back jasmine to life

_data/devices/mi439.yml, pages/build/mi439.md, pages/info/mi439.md, pages/install/mi439.md, pages/install/olivewood.md, pages/update/mi439.md, pages/update/olivewood.md, pages/upgrade/mi439.md, pages/upgrade/olivewood.md
* Update name
Signed-off-by: shield44 <shield44@pixelexperience.org>
=> wiki: Switch to mi439

_data/devices/apollo.yml
* AOSP Recovery ftw
* Update CPU Freq info
* Update camera info
* Update storage info
Signed-off-by: Henrique Pereira <hlcereira@pixelexperience.org>
=> wiki: Update apollo info

_data/devices/mojito.yml
=> wiki: mojito: install vendor_boot before recovery

_data/devices/instantnoodle.yml, _includes/templates/device_specific/before_recovery_install_instantnoodle.md
Signed-off-by: The Vision <x@zlew.tf>
Change-Id: I6a3c4178094ab6b0ba9e48e6c5e511ce84f5e36d
=> wiki: instantnoodle: Update for Android 13

_data/devices/veux.yml, pages/build/veux.md, pages/info/veux.md, pages/install/veux.md, pages/update/veux.md, pages/upgrade/veux.md
Signed-off-by: kleidione <kleidione@gmail.com>
=> wiki: Add device Poco X4 Pro 5G (veux/peux)

_data/devices/veux.yml
Signed-off-by: kleidione <kleidione@gmail.com>
=> wiki: Fix device image preview loading

_data/devices/fog.yml, pages/build/fog.md, pages/info/fog.md, pages/install/fog.md, pages/update/fog.md, pages/upgrade/fog.md
Signed-off-by: shield44 <shield44@pixelexperience.org>
=> wiki: Add Redmi 10/10C/10 Power

_includes/templates/device_specific/before_recovery_install_dtbo_and_vendor_boot.md
Signed-off-by: Henrique Pereira <hlcpereira@outlook.com.br>
=> wiki: Account devices with needs to flash dtbo and vendor_boot before recovery

_data/devices/berlin.yml, pages/build/berlin.md, pages/info/berlin.md, pages/install/berlin.md, pages/update/berlin.md, pages/upgrade/berlin.md, test/schema-06.yml
Signed-off-by: kleidione <kleidione@gmail.com>
=> wiki: Add Moto Edge 20 (berlin)

_data/devices/lavender.yml
- Fix model name as well
Change-Id: Iaf02cfb40053dfeb258c08e400d921c99a8ba307
=> wiki: Drop custom recovery for lavender

_includes/alerts/specific/tip_adb_flash_success.html
Add Total xfer: 0.98x as a success output
=> wiki: Update adb install tip

_data/devices/instantnoodle.yml
Signed-off-by: The Vision <zlewchan@outlook.com>
Change-Id: I45555e6ca33f4ef90f8039b6f2ee132b0ee85534
=> wiki: instantnoodle: Ships firmware

_data/devices/rosemary.yml
Signed-off-by: Beru Hinode <windowz414@1337.lgbt>
=> rosemary: Cleanup YAML

_data/devices/citrus.yml, _data/devices/lime.yml, pages/build/citrus.md, pages/build/lime.md, pages/info/citrus.md, pages/info/lime.md, pages/install/chime.md, pages/install/citrus.md, pages/install/lime.md, pages/update/chime.md, pages/update/citrus.md, pages/update/lime.md, pages/upgrade/chime.md, pages/upgrade/citrus.md, pages/upgrade/lime.md
Signed-off-by: HeroBuxx <me@buxxed.tk>
=> wiki: Deunify POCO M3 and Redmi 8T

_data/devices/venus.yml
Signed-off-by: Chenyang Zhong <zhongcy95@gmail.com>
=> venus: update the link for vendor_boot.img

_data/devices/cheeseburger.yml
* Also add myself as maintainer of thirteen and thirteen plus
=> wiki: cheeseburger: Don't use custom recovery

pages/contributing_wiki.md
Improved a line and corrected a grammatical mistake.
=> Improved the contributing_wiki.md

_data/devices/beckham.yml, _includes/templates/device_specific/before_install_custom_beckham.md
Change-Id: I47596974d723b37f0f5eb2209301d9162c272d5d
=> Retrofit guide for beckham

_data/devices/chiron.yml, _includes/templates/device_specific/before_install_custom_chiron.md
Change-Id: I62ea4673e1539f6c88371b364be667ad1d9491b9
=> wiki: Add retrofit guide for chiron

_includes/templates/device_specific/before_install_martini.md
We ship with fw now, no need for the long fw flashing guide
=> martini: Update install instructions

_data/devices/mars.yml
* https://review.lineageos.org/c/LineageOS/lineage_wiki/+/361429
=> wiki: Updating Mars peripherals from LineageOS wiki

_data/devices/berlin.yml, _data/devices/nio.yml
=> motorola: Add correct links for required files

_data/devices/mars.yml, _data/devices/venus.yml
* wiki_blobs_mars|wiki_blobs_venus --> wiki_blobs_sm8350
=> wiki: mars/venus: Unity wiki_blobs repo
